name: motomatrix
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_database: ^10.2.7
  flutter_riverpod: ^2.4.3
  flutter_stripe: ^9.4.0
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  html: ^0.15.4
  tflite_flutter: ^0.10.2
  draggable_home: ^1.0.5
  dart_openai: ^4.0.0
  flutter_chat_ui: ^1.6.9
  flutter_chat_types: ^3.6.2
  scrollable_positioned_list: ^0.3.8
  scroll_to_index: ^3.0.1
  dash_chat: ^1.1.16



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/genesis.png
    - assets/images/mygarage.png
    - assets/images/splash.png
    - assets/images/obd2.png
    - assets/images/user_profile.png
    - assets/images/vin_decoder.png
    - assets/images/dtc_info.png
    - assets/images/common_fix.png
    - assets/images/oem_request.png
    - assets/images/settings.png
    - assets/lite-model_qat_mobilebert_xs_qat_lite_1.tflite
    - assets/logos/optimized/
    - assets/codes.json
